In [1]:
import numpy as np

In [2]:
A = np.array([[100, 98, 0,75], [23,45,67, 87],[45,565, 74, 73]])

In [3]:
A

array([[100,  98,   0,  75],
       [ 23,  45,  67,  87],
       [ 45, 565,  74,  73]])

### Vertical percentage 

In [4]:
cal = A.sum(axis = 0)
print(cal)

[168 708 141 235]


In [8]:
percent = 100*A/cal
percent

array([[59.52380952, 13.84180791,  0.        , 31.91489362],
       [13.69047619,  6.3559322 , 47.5177305 , 37.0212766 ],
       [26.78571429, 79.80225989, 52.4822695 , 31.06382979]])

### Horizontal sum

In [12]:
cal1 = A.sum(axis  = 1)
print(cal1)

[273 222 757]


In [29]:
percentVer = 100*(A/cal1.reshape(3,1))
print(percentVer)

[[36.63003663 35.8974359   0.         27.47252747]
 [10.36036036 20.27027027 30.18018018 39.18918919]
 [ 5.94451783 74.63672391  9.77542933  9.64332893]]


### Other Broadcasting 

In [30]:
A + .0001

array([[1.000001e+02, 9.800010e+01, 1.000000e-04, 7.500010e+01],
       [2.300010e+01, 4.500010e+01, 6.700010e+01, 8.700010e+01],
       [4.500010e+01, 5.650001e+02, 7.400010e+01, 7.300010e+01]])

In [32]:
A

array([[100,  98,   0,  75],
       [ 23,  45,  67,  87],
       [ 45, 565,  74,  73]])

In [35]:
A + [.1,.01, .001,.0001] 

array([[1.00100e+02, 9.80100e+01, 1.00000e-03, 7.50001e+01],
       [2.31000e+01, 4.50100e+01, 6.70010e+01, 8.70001e+01],
       [4.51000e+01, 5.65010e+02, 7.40010e+01, 7.30001e+01]])

In [34]:
A + [[.1],[.01], [.001]]

array([[1.00100e+02, 9.81000e+01, 1.00000e-01, 7.51000e+01],
       [2.30100e+01, 4.50100e+01, 6.70100e+01, 8.70100e+01],
       [4.50010e+01, 5.65001e+02, 7.40010e+01, 7.30010e+01]])

In [36]:
B = np.array([1,2,3])

In [38]:
B.shape

(3,)

In [40]:
B.T.shape

(3,)

In [44]:
B*B.T

array([1, 4, 9])

In [45]:
## inner product
np.dot(B, B.T)

14

In [49]:
C =np.array([1,2,3]).reshape(1,3)
D =np.array([1,2,3]).reshape(3,1)

In [51]:
C

array([[1, 2, 3]])

In [48]:
C.shape

(1, 3)

In [50]:
D

array([[1],
       [2],
       [3]])

In [53]:
np.dot(C.T,C)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [58]:
a = np.random.randn(5,1)  #column vector
b = np.random.randn(1,5)  #row vector

In [59]:
a

array([[-0.60418094],
       [ 0.08724863],
       [ 1.37303178],
       [ 1.17806518],
       [ 1.57316189]])

In [60]:
b

array([[-0.12904235,  2.26862542,  1.00973159, -0.54980508, -0.55726685]])

In [63]:
assert(a.shape == (1,5)) # when expected shape is not passed

AssertionError: 

In [62]:
assert(a.shape == (5,1))

In [80]:
i1= np.random.rand(2,3)
i2= np.random.rand(3,2)

In [68]:
i2.shape

(3, 2)

In [71]:
np.matmul(i1,i2)

array([[0.84007272, 0.68774449],
       [1.08672068, 0.82961325]])

In [74]:
i3= np.random.rand(2,3)
i4= np.random.rand(2,1)

In [75]:
i3+i4

array([[0.53525347, 0.9096191 , 1.3242382 ],
       [1.13930816, 0.52551173, 0.87650799]])

In [77]:
j = i3*i4
j

array([[0.02581744, 0.20613123, 0.40583317],
       [0.25563446, 0.06706353, 0.17489682]])

In [78]:
j.shape

(2, 3)

In [81]:
np.dot(i1,i2)

array([[0.63395969, 1.29451857],
       [0.61402877, 1.21357138]])

In [88]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [93]:
a

array([[-2.31920829,  0.09972052, -0.66350214],
       [-0.66432245, -0.2422271 , -0.82630949],
       [ 0.21102472,  1.61878244,  0.1867402 ]])

In [94]:
b

array([[-0.24273117],
       [-1.27596507],
       [-0.66259118]])

In [95]:
c

array([[ 0.56294415, -0.02420528,  0.16105265],
       [ 0.84765224,  0.30907333,  1.05434205],
       [-0.13982312, -1.07259097, -0.12373241]])